# Powerlevel10k configuration: Purple theme, no custom font required

# --- Prompt Style ---
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time)

# --- Colors ---
typeset -g POWERLEVEL9K_COLOR_SCHEME='dark'
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=244

# Main accent color: purple
typeset -g P10K_PURPLE='#a259f7'

# --- Segment Colors ---
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=white
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$P10K_PURPLE

typeset -g POWERLEVEL9K_DIR_FOREGROUND=white
typeset -g POWERLEVEL9K_DIR_BACKGROUND=$P10K_PURPLE
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=white
typeset -g POWERLEVEL9K_DIR_ANCHOR_BACKGROUND=$P10K_PURPLE

typeset -g POWERLEVEL9K_VCS_FOREGROUND=white
typeset -g POWERLEVEL9K_VCS_BACKGROUND=$P10K_PURPLE

typeset -g POWERLEVEL9K_STATUS_FOREGROUND=white
typeset -g POWERLEVEL9K_STATUS_BACKGROUND=$P10K_PURPLE

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=white
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=$P10K_PURPLE

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=white
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=$P10K_PURPLE

typeset -g POWERLEVEL9K_TIME_FOREGROUND=white
typeset -g POWERLEVEL9K_TIME_BACKGROUND=$P10K_PURPLE
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

# --- Symbols (ASCII only, no custom font) ---
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='[ZSH]'
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='*'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='↓'
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='↑'
typeset -g POWERLEVEL9K_VCS_CLEAN_ICON='✔'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_ICON='!'
typeset -g POWERLEVEL9K_VCS_TAG_ICON='🏷'

# --- Prompt Characters ---
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='❯'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=$P10K_PURPLE
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND=red
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_CONTENT='❯'

# --- Misc ---
typeset -g POWERLEVEL9K_SHOW_RULER=false
typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# --- Hide icons that require patched font ---
typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
typeset -g POWERLEVEL9K_ICON_PADDING=none
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

# --- Final touch: minimal, purple, ASCII-friendly prompt ---
# You can further customize by editing this file.

# End of ~/.p10k.zsh
