# Starship Configuration File - XCAD Theme
# This file customizes the appearance and behavior of the Starship prompt
# Starship is a fast, customizable shell prompt written in Rust
# Color scheme: xcad - Purple/Blue gradient theme

# Main format string - defines the overall layout of the prompt
# Uses powerline-style separators () and background colors matching xcad theme
format = """
[░▒▓](#5C78FF)\
[ 👺 ](bg:#5C78FF fg:#121212)\
[](bg:#2B4FFF fg:#5C78FF)\
$directory\
[](fg:#2B4FFF bg:#2883FF)\
$git_branch\
$git_status\
[](fg:#2883FF bg:#7129FF)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#7129FF bg:#A52AFF)\
$time\
[](fg:#A52AFF)\
$fill\
\n$character"""

# Right format - displays modules on the right side of the terminal
right_format = """
[](fg:#A52AFF)\
$cmd_duration\
[](fg:#7129FF bg:#A52AFF)\
$status\
[](fg:#2883FF bg:#7129FF)\
$jobs\
[](fg:#2B4FFF bg:#2883FF)\
$battery\
[](fg:#5C78FF bg:#2B4FFF)\
$username\
[](fg:#5C78FF)"""

# Directory module - shows current working directory
[directory]
style = "fg:#F1F1F1 bg:#2B4FFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Directory substitutions - replace common folder names with icons
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Git branch module - shows current git branch
[git_branch]
symbol = ""
style = "bg:#2883FF"
format = '[[ $symbol $branch ](fg:#F1F1F1 bg:#2883FF)]($style)'

# Git status module - shows git repository status
[git_status]
style = "bg:#2883FF"
format = '[[($all_status$ahead_behind )](fg:#F1F1F1 bg:#2883FF)]($style)'

# Node.js module - shows Node.js version when in a Node.js project
[nodejs]
symbol = ""
style = "bg:#7129FF"
format = '[[ $symbol ($version) ](fg:#F1F1F1 bg:#7129FF)]($style)'

# Rust module - shows Rust version when in a Rust project
[rust]
symbol = ""
style = "bg:#7129FF"
format = '[[ $symbol ($version) ](fg:#F1F1F1 bg:#7129FF)]($style)'

# Go (Golang) module - shows Go version when in a Go project
[golang]
symbol = ""
style = "bg:#7129FF"
format = '[[ $symbol ($version) ](fg:#F1F1F1 bg:#7129FF)]($style)'

# PHP module - shows PHP version when in a PHP project
[php]
symbol = ""
style = "bg:#7129FF"
format = '[[ $symbol ($version) ](fg:#F1F1F1 bg:#7129FF)]($style)'

# Python module - shows Python version when in a Python project
[python]
symbol = ""
style = "bg:#7129FF"
format = '[[ $symbol ($version) ](fg:#F1F1F1 bg:#7129FF)]($style)'

# Time module - shows current time
[time]
disabled = false
time_format = "%R"
style = "bg:#A52AFF"
format = '[[  $time ](fg:#F1F1F1 bg:#A52AFF)]($style)'

# Command duration module - shows how long the last command took
[cmd_duration]
min_time = 2000
show_milliseconds = false
style = "fg:#F1F1F1 bg:#A52AFF"
format = "[ took $duration ]($style)"

# Status module - shows exit code of last command (when non-zero)
[status]
disabled = false
symbol = "✗"
success_symbol = ""
style = "fg:#F1F1F1 bg:#7129FF"
format = '[[ $symbol $status ]($style)]($style)'

# Jobs module - shows number of background jobs
[jobs]
symbol = ""
style = "fg:#F1F1F1 bg:#2883FF"
format = '[[ $symbol $number ]($style)]($style)'

# Battery module - shows battery status (on laptops)
[battery]
display = [
    { threshold = 20, style = "fg:#F1F1F1 bg:#2B4FFF" },
]
format = '[[ $symbol $percentage ]($style)]($style)'

# Username module - shows current username
[username]
format = '[ $user ](fg:#121212 bg:#5C78FF)'
show_always = false

# Fill module - fills the remaining space on the line
[fill]
symbol = "─"
style = "fg:#666666"

# Character module - prompt character
[character]
success_symbol = "[❯](bold #28B9FF)"
error_symbol = "[❯](bold #BA5AFF)"
